<script setup lang="ts">
import { computed } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { ArrowUpRightIcon, CpuChipIcon, CubeTransparentIcon, ServerStackIcon, SignalIcon, CircleStackIcon } from '@heroicons/vue/24/outline'
import PageHeader from '../components/PageHeader.vue'
import StatCard from '../components/StatCard.vue'
import { api } from '../lib/api'
const { data, isLoading } = useQuery({ queryKey: ['dashboard'], queryFn: api.dashboard }); const dashboard = computed(() => data.value)
const relative = (timestamp: string) => { const minutes = Math.max(1, Math.round((Date.now() - new Date(timestamp).getTime()) / 60000)); return minutes < 60 ? `${minutes}m ago` : `${Math.round(minutes / 60)}h ago` }
</script>

<template>
  <PageHeader eyebrow="Workspace overview" title="Good morning, Alex" description="Here’s what’s happening across your platform today."><button class="button-secondary"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4 12a8 8 0 0 1 14.4-4.8M20 12a8 8 0 0 1-14.4 4.8M18 3v4h-4M6 21v-4h4" stroke-linecap="round" stroke-linejoin="round" /></svg>Refresh</button></PageHeader>
  <div v-if="isLoading" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div v-for="n in 4" :key="n" class="h-32 animate-pulse rounded-2xl bg-panel" /></div>
  <template v-else-if="dashboard">
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Cluster status" :value="dashboard.cluster.status" :detail="dashboard.cluster.version" :icon="SignalIcon" /><StatCard label="Running pods" :value="dashboard.resources.runningPods" detail="Across all namespaces" :icon="CubeTransparentIcon" accent="bg-violet/10 text-violet" /><StatCard label="Deployments" :value="dashboard.resources.runningDeployments" detail="All workloads healthy" :icon="ServerStackIcon" accent="bg-sky-400/10 text-sky-300" /><StatCard label="CPU usage" :value="`${dashboard.resources.cpuUsagePercent}%`" detail="Cluster average" :icon="CpuChipIcon" accent="bg-amber-400/10 text-amber-300" /></div>
    <div class="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section class="surface p-5 sm:p-6"><div class="flex items-center justify-between"><div><p class="eyebrow">Resource utilization</p><h2 class="mt-2 text-base font-semibold text-white">Cluster capacity</h2></div><button class="button-ghost text-xs">Last 24 hours <ArrowUpRightIcon class="h-3.5 w-3.5" /></button></div><div class="mt-8 grid gap-7 sm:grid-cols-2"><div><div class="flex items-end justify-between"><span class="text-sm font-medium text-slate-300">CPU</span><span class="font-mono text-sm text-white">{{ dashboard.resources.cpuUsagePercent }}%</span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-ink"><div class="h-full rounded-full bg-accent" :style="{ width: `${dashboard.resources.cpuUsagePercent}%` }" /></div><p class="mt-2 text-xs text-slate-600">12.6 cores of 32 allocatable</p></div><div><div class="flex items-end justify-between"><span class="text-sm font-medium text-slate-300">Memory</span><span class="font-mono text-sm text-white">{{ dashboard.resources.memoryUsagePercent }}%</span></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-ink"><div class="h-full rounded-full bg-violet" :style="{ width: `${dashboard.resources.memoryUsagePercent}%` }" /></div><p class="mt-2 text-xs text-slate-600">34.6 GiB of 64 GiB allocatable</p></div></div><div class="mt-8 grid grid-cols-3 divide-x divide-line rounded-xl border border-line bg-ink/40 py-4"><div class="px-4"><p class="text-xl font-bold text-white">{{ dashboard.resources.nodes }}</p><p class="mt-1 text-xs text-slate-600">Nodes</p></div><div class="px-4"><p class="text-xl font-bold text-white">{{ dashboard.cluster.namespaces }}</p><p class="mt-1 text-xs text-slate-600">Namespaces</p></div><div class="px-4"><p class="text-xl font-bold text-white">{{ dashboard.cluster.storageClasses }}</p><p class="mt-1 text-xs text-slate-600">Storage classes</p></div></div></section><section class="surface p-5 sm:p-6"><div class="flex items-center justify-between"><div><p class="eyebrow">Kubernetes</p><h2 class="mt-2 text-base font-semibold text-white">Nodes</h2></div><router-link to="/settings" class="button-ghost text-xs">View details <ArrowUpRightIcon class="h-3.5 w-3.5" /></router-link></div><div class="mt-5 space-y-4"><div v-for="node in dashboard.nodes" :key="node.name" class="flex items-center gap-3"><div class="grid h-8 w-8 place-items-center rounded-lg bg-accent/10 text-accent"><ServerStackIcon class="h-4 w-4" /></div><div class="min-w-0 flex-1"><div class="flex items-center justify-between gap-2"><p class="truncate text-sm font-medium text-slate-200">{{ node.name }}</p><span class="text-[11px] text-accent">{{ node.status }}</span></div><div class="mt-1.5 flex gap-4 text-[11px] text-slate-600"><span>CPU {{ node.cpu }}</span><span>MEM {{ node.memory }}</span></div></div></div></div></section></div>
    <div class="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section class="surface overflow-hidden"><div class="flex items-center justify-between p-5 sm:p-6"><div><p class="eyebrow">Activity stream</p><h2 class="mt-2 text-base font-semibold text-white">Recent events</h2></div><button class="button-ghost text-xs">View all <ArrowUpRightIcon class="h-3.5 w-3.5" /></button></div><div class="divide-y divide-line/60"><div v-for="event in dashboard.recentEvents" :key="event.message" class="flex gap-3 px-5 py-4 sm:px-6"><div :class="['mt-1 h-2 w-2 shrink-0 rounded-full', event.type === 'Warning' ? 'bg-amber-300' : 'bg-accent']" /><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center justify-between gap-2"><p class="text-sm text-slate-300">{{ event.message }}</p><span class="text-[11px] text-slate-600">{{ relative(event.timestamp) }}</span></div><p class="mt-1 text-xs text-slate-600">{{ event.reason }} · <span class="text-slate-500">{{ event.namespace }}</span></p></div></div></div></section><section class="surface p-5 sm:p-6"><div class="flex items-center justify-between"><div><p class="eyebrow">Quick access</p><h2 class="mt-2 text-base font-semibold text-white">Jump back in</h2></div><CircleStackIcon class="h-5 w-5 text-slate-600" /></div><div class="mt-5 space-y-2"><router-link to="/applications" class="group flex items-center justify-between rounded-xl border border-line bg-ink/30 p-3 transition hover:border-accent/40"><span><span class="block text-sm font-medium text-slate-300">Deploy an application</span><span class="mt-1 block text-xs text-slate-600">Create a new workload</span></span><ArrowUpRightIcon class="h-4 w-4 text-slate-600 transition group-hover:text-accent" /></router-link><router-link to="/environments" class="group flex items-center justify-between rounded-xl border border-line bg-ink/30 p-3 transition hover:border-accent/40"><span><span class="block text-sm font-medium text-slate-300">Create environment</span><span class="mt-1 block text-xs text-slate-600">A safe space for testing</span></span><ArrowUpRightIcon class="h-4 w-4 text-slate-600 transition group-hover:text-accent" /></router-link></div></section></div>
  </template>
</template>

