<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ArrowDownIcon, PauseIcon, PlayIcon, MagnifyingGlassIcon, CommandLineIcon } from '@heroicons/vue/24/outline'
import PageHeader from '../components/PageHeader.vue'
import { api } from '../lib/api'
import type { Application, Logs } from '../types'
const route = useRoute(); const apps = ref<Application[]>([]); const selectedApp = ref(''); const logs = ref<Logs | null>(null); const query = ref(''); const autoScroll = ref(true); const loading = ref(false)
onMounted(async () => { apps.value = await api.applications(); selectedApp.value = typeof route.query.application === 'string' && apps.value.some((a) => a.name === route.query.application) ? route.query.application : apps.value[0]?.name ?? ''; await load() })
async function load() { if (!selectedApp.value) return; loading.value = true; logs.value = await api.logs(selectedApp.value); loading.value = false }
const filteredLines = computed(() => logs.value?.lines.filter((line) => `${line.level} ${line.message}`.toLowerCase().includes(query.value.toLowerCase())) ?? [])
</script>

<template><PageHeader eyebrow="Observability" title="Logs" description="Inspect pod output in context, with enough signal to understand what changed."><div class="flex items-center gap-2"><button :class="['button-secondary text-xs', autoScroll ? 'border-accent/30 text-accent' : '']" @click="autoScroll = !autoScroll"> <component :is="autoScroll ? PlayIcon : PauseIcon" class="h-4 w-4" />{{ autoScroll ? 'Auto-scroll on' : 'Auto-scroll off' }}</button><button class="button-secondary text-xs" @click="load"><ArrowDownIcon class="h-4 w-4" />Refresh</button></div></PageHeader><div class="surface overflow-hidden"><div class="flex flex-col gap-3 border-b border-line/70 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div class="flex flex-1 items-center gap-3"><div class="grid h-8 w-8 place-items-center rounded-lg bg-accent/10 text-accent"><CommandLineIcon class="h-4 w-4" /></div><select v-model="selectedApp" class="field h-9 max-w-xs font-mono text-xs" @change="load"><option v-for="app in apps" :key="app.id" :value="app.name">{{ app.name }}</option></select><span v-if="logs" class="hidden text-xs text-slate-600 sm:inline">{{ logs.pod }}</span></div><div class="relative"><MagnifyingGlassIcon class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-600" /><input v-model="query" class="field h-9 pl-9 text-xs sm:w-64" placeholder="Search logs..." /></div></div><div class="min-h-[420px] bg-[#07101d] p-4 font-mono text-xs leading-7 sm:p-6"><div v-if="loading" class="text-slate-600">Connecting to pod stream...</div><div v-else-if="!logs" class="grid h-80 place-items-center text-slate-600">Select an application to view logs.</div><div v-else-if="filteredLines.length === 0" class="text-slate-600">No log lines match your search.</div><div v-for="(line, index) in filteredLines" :key="`${line.timestamp}-${index}`" class="flex gap-3 whitespace-pre-wrap"><span class="shrink-0 select-none text-slate-700">{{ line.timestamp }}</span><span :class="line.level === 'ERROR' ? 'text-rose-300' : 'text-accent'">{{ line.level }}</span><span class="text-slate-400">{{ line.message }}</span></div><div v-if="autoScroll && logs" class="mt-3 flex items-center gap-2 text-slate-700"><span class="h-1.5 w-1.5 animate-pulse rounded-full bg-accent" />listening for new lines</div></div></div></template>

